auth:
  admin:
    access: true
    users: <hubAdminUsersList>
  azuread:
    callbackUrl: https://hub.bridge-data-platform.turing.ac.uk/hub/oauth_callback
    clientId: <azureADClientId>
    clientSecret: <azureADClientSecret>
    tenantId: <azureADTenantId>
  type: azuread
  whitelist:
    users:
    - ^(?!\w+).*$
hub:
  networkPolicy:
    enabled: true
prePuller:
  continuous:
    enabled: true
proxy:
  https:
    hosts:
    - hub.bridge-data-platform.turing.ac.uk
    letsencrypt:
      contactEmail: <letsEncryptContactEmail>
  networkPolicy:
    enabled: true
  secretToken: <proxySecretToken>
scheduling:
  podPriority:
    enabled: true
  userScheduler:
    enabled: true
singleuser:
  corePods:
    nodeAffinity:
      matchNodePurpose: require
  cpu:
    guarantee: 0.5
    limit: 0.5
  defaultUrl: /lab
  image:
    name: jupyter/minimal-notebook
    tag: hub-1.4.2
  memory:
    guarantee: 1G
    limit: 1G
  networkPolicy:
    egress:
    - ports:
      - port: 53
        protocol: UDP
    - ports:
      - port: 80
        protocol: TCP
    - ports:
      - port: 443
        protocol: TCP
    enabled: true
  profileList:
  - default: true
    description: A simple Python environment
    display_name: Minimal environment
  - description: Includes Python, R, and Julia
    display_name: Data Science Environment
    kubespawner_override:
      image: jupyter/datascience-notebook:ubuntu-20.04
  - description: 'Custom image built from the JupyterHub environment repo using repo2docker:
      https://github.com/alan-turing-institute/bridge-data-environment'
    display_name: Custom repo2docker image
    kubespawner_override:
      image: turinginst/bridge-data-env:2020.06.22-8170d9c
