# Authenticate users with GitHub
auth:
  type: github
  github:
    clientId: "<githubClientId>"
    clientSecret: "<githubClientSecret>"
    callbackUrl: "http://<jupyterhubIp>/hub/oauth_callback"
  admin:
    access: true
    users: ["edaub", "sgibson91"]
  whitelist:
    users: []

# Cull inactive pods to free up resources
cull:
  enabled: true
  timeout: 3600
  every: 300

hub:
  # Use JupyterLab interface by default
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

# Pull images as soon as a node is added to reduce wait time
prePuller:
  continuous:
    enabled: true

proxy:
  secretToken: "<proxySecretToken>"

scheduling:
  # Allow cluster to scale up in anticipation of users arrival
  # (reduces wait time)
  podPriority:
    enabled: true
  # Pack users onto nodes so that empty ones can be scaled down
  userScheduler:
    enabled: true

# Set resource limits to efficiently pack users onto nodes
singleuser:
  cpu:
    limit: 0.5
    guarantee: 0.5
  memory:
    limit: 1G
    guarantee: 1G
  # Use JupyterLab interface by default
  defaultUrl: "/lab"
  # Mount external NFS server to user pods as a shareddata folder
  storage:
    extraVolumes:
      - name: bridge-shared-data
        persistentVolumeClaim:
          claimName: bridge-shared-data-pvc
    extraVolumeMounts:
      - name: bridge-shared-data
        mountPath: /home/jovyan/data
  # Define the default image
  image:
    name: jupyter/minimal-notebook
    tag: e255f1aa00b2
  profileList:
    - display_name: "Minimal environment"
      description: "A simple Python environment"
      default: true
    - display_name: "Data Science Environment"
      description: "Includes Python, R, and Julia"
      kubespawner_override:
        image: jupyter/datascience-notebook:e255f1aa00b2
    - display_name: "Custom repo2docker image"
      # yamllint disable-line rule:line-length
      description: "Custom image built from the JupyterHub environment repo using repo2docker: https://github.com/alan-turing-institute/bridge-data-environment"
      kubespawner_override:
        image: turinginst/bridge-data-env:2020.03.10-00ef4f7
