auth:
  admin:
    access: true
    users:
    - edaub
    - sgibson91
  github:
    callbackUrl: http://<jupyterhubIp>/hub/oauth_callback
    clientId: <githubClientId>
    clientSecret: <githubClientSecret>
  type: github
  whitelist:
    users:
    - ^(?!\w+).*$
cull:
  enabled: true
  every: 300
  timeout: 3600
hub:
  networkPolicy:
    enabled: true
prePuller:
  continuous:
    enabled: true
proxy:
  networkPolicy:
    enabled: true
  secretToken: <proxySecretToken>
scheduling:
  podPriority:
    enabled: true
  userScheduler:
    enabled: true
singleuser:
  corePods:
    nodeAffinity:
      matchNodePurpose: require
  cpu:
    guarantee: 0.5
    limit: 0.5
  defaultUrl: /lab
  image:
    name: jupyter/minimal-notebook
    tag: dc9744740e12
  memory:
    guarantee: 1G
    limit: 1G
  networkPolicy:
    egress:
    - ports:
      - port: 53
        protocol: UDP
    - ports:
      - port: 80
        protocol: TCP
    - ports:
      - port: 443
        protocol: TCP
    enabled: true
  profileList:
  - default: true
    description: A simple Python environment
    display_name: Minimal environment
  - description: Includes Python, R, and Julia
    display_name: Data Science Environment
    kubespawner_override:
      image: jupyter/datascience-notebook:dc9744740e12
  - description: 'Custom image built from the JupyterHub environment repo using repo2docker:
      https://github.com/alan-turing-institute/bridge-data-environment'
    display_name: Custom repo2docker image
    kubespawner_override:
      image: turinginst/bridge-data-env:2020.04.14-eb5bb8f
