auth:
  admin:
    access: true
    users:
    - edaub
    - sgibson91
  github:
    callbackUrl: http://<jupyterhubIp>/hub/oauth_callback
    clientId: <githubClientId>
    clientSecret: <githubClientSecret>
  type: github
  whitelist:
    users: []
cull:
  enabled: true
  every: 300
  timeout: 3600
hub:
  extraConfig:
    jupyterlab: 'c.Spawner.cmd = [''jupyter-labhub'']

      '
prePuller:
  continuous:
    enabled: true
proxy:
  secretToken: <proxySecretToken>
scheduling:
  podPriority:
    enabled: true
  userScheduler:
    enabled: true
singleuser:
  corePods:
    nodeAffinity:
      matchNodePurpose: require
  cpu:
    guarantee: 0.5
    limit: 0.5
  defaultUrl: /lab
  image:
    name: jupyter/minimal-notebook
    tag: e255f1aa00b2
  memory:
    guarantee: 1G
    limit: 1G
  profileList:
  - default: true
    description: A simple Python environment
    display_name: Minimal environment
  - description: Includes Python, R, and Julia
    display_name: Data Science Environment
    kubespawner_override:
      image: jupyter/datascience-notebook:e255f1aa00b2
  - description: 'Custom image built from the JupyterHub environment repo using repo2docker:
      https://github.com/alan-turing-institute/bridge-data-environment'
    display_name: Custom repo2docker image
    kubespawner_override:
      image: turinginst/bridge-data-env:2020.03.10-c2c199f
  storage:
    extraVolumeMounts:
    - mountPath: /home/jovyan/data
      name: bridge-shared-data
    extraVolumes:
    - name: bridge-shared-data
      persistentVolumeClaim:
        claimName: bridge-shared-data-pvc
