# Authenticate users with GitHub
auth:
  type: github
  github:
    clientId: "<githubClientId>"
    clientSecret: "<githubClientSecret>"
    callbackUrl: "http://<jupyterhubIp>/hub/oauth_callback"
  admin:
    access: true
    users: ["edaub", "sgibson91"]
  whitelist:
    users:
      - "^(?!\\w+).*$"

# Cull inactive pods to free up resources
cull:
  enabled: true
  timeout: 3600
  every: 300

hub:
  # Use JupyterLab interface by default
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
  networkPolicy:
    enabled: true

# Pull images as soon as a node is added to reduce wait time
prePuller:
  continuous:
    enabled: true

proxy:
  secretToken: "<proxySecretToken>"
  networkPolicy:
    enabled: true

scheduling:
  # Allow cluster to scale up in anticipation of users arrival
  # (reduces wait time)
  podPriority:
    enabled: true
  # Pack users onto nodes so that empty ones can be scaled down
  userScheduler:
    enabled: true

singleuser:
  # Enable network policy
  networkPolicy:
    enabled: true
    # Restrict outbound traffic to DNS, HTTP and HTTPS
    egress:
      - ports:
          - port: 53
            protocol: UDP
      - ports:
          - port: 80
            protocol: TCP
      - ports:
          - port: 443
            protocol: TCP
  # Require core pods to stay on labelled node
  corePods:
    nodeAffinity:
      matchNodePurpose: require
  # Set CPU and memory limits to efficiently pack users onto nodes
  cpu:
    limit: 0.5
    guarantee: 0.5
  memory:
    limit: 1G
    guarantee: 1G
  # Use JupyterLab interface by default
  defaultUrl: "/lab"
  # Define the default image
  image:
    name: jupyter/minimal-notebook
    tag: dc9744740e12
  # Create profile lists for users to choose from
  profileList:
    - display_name: "Minimal environment"
      description: "A simple Python environment"
      default: true
    - display_name: "Data Science Environment"
      description: "Includes Python, R, and Julia"
      kubespawner_override:
        image: jupyter/datascience-notebook:dc9744740e12
    - display_name: "Custom repo2docker image"
      # yamllint disable-line rule:line-length
      description: "Custom image built from the JupyterHub environment repo using repo2docker: https://github.com/alan-turing-institute/bridge-data-environment"
      kubespawner_override:
        image: turinginst/bridge-data-env:2020.03.10-c2c199f
  storage:
      extraVolumes:
        - name: bridge-shared-data
          persistentVolumeClaim:
            claimName: bridge-shared-data-pvc
      extraVolumeMounts:
        - name: bridge-shared-data
          mountPath: /home/shared
