# Pipeline is triggered on pushes to master
# and does NOT run in Pull Requests
trigger:
  - master
pr: none

# Schedule a Ubuntu VM to run the job
pool:
  vmImage: ubuntu-latest

variables:
  kubernetes_cluster_name: 'bridge-data-cluster'
  kubernetes_cluster_resource_group: 'bridge-data-platform'
  kubernetes_version: '1.14.8'

# Construct the job to deploy the upgrade
jobs:
  - job: DeployHelmUpgrade
    steps:
      - task: KubectlInstaller@0
        displayName: 'Install kubectl $(KUBERNETES_VERSION)'
        inputs:
          kubectlVersion: $(KUBERNETES_VERSION)

      - task: AzureCLI@1
        displayName: 'Merge kubectl config'
        inputs:
          azureSubscription: 'bridge-data-platform-scn'
          scriptLocation: 'inlineScript'
          inlineScript: 'az aks get-credentials -n $(KUBERNETES_CLUSTER_NAME) -g $(KUBERNETES_CLUSTER_RESOURCE_GROUP)'

      - task: AzureKeyVault@1
        displayName: 'Pull Secrets from Key Vault'
        inputs:
          azureSubscription: 'bridge-data-platform-scn'
          KeyVaultName: 'bridge-data-keyvault'
          SecretsFilter: 'proxySecretToken'

      - task: Bash@3
        displayName: 'Create .secret/ directory'
        inputs:
          targetType: 'inline'
          script: 'mkdir -p .secret'

      - task: Bash@3
        displayName: 'Generate .secret/config.yaml'
        inputs:
          targetType: 'inline'
          script: |
            sed -e "s/<proxySecretToken>/$(proxySecretToken)/" \
            config/config-template.yaml > .secret/config.yaml
