schedules:
  - cron: "0 0 * * *"
    displayName: Daily Docker image tag update
    branches:
      include:
        - master
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  keyvault_name: 'bridge-data-keyvault'
  repo_name: 'bridge-data-platform'
  repo_owner: 'alan-turing-institute'
  service_connection: ' bridge-data-platform-scn'
  token_name: 'githubAccessToken'
  working_dir: 'scripts'

jobs:
  - job: UpdateDockerImageTags
    steps:
      - task: UsePythonVersion@0
        displayName: 'Install Python 3.7'
        inputs:
          versionSpec: '3.7'
          addToPath: true

      - script: 'python -m pip install -U pip setuptools wheel'
        displayName: 'Upgrade Python tools'

      - script: 'python -m pip install -r requirements.txt'
        displayName: 'Install UpdateDockerTags dependencies'
        workingDirectory: $(WORKING_DIR)

      - task: AzureKeyVault@1
        displayName: 'Pull secret token from Key Vault'
        inputs:
          azureSubscription: $(SERVICE_CONNECTION)
          KeyVaultName: $(KEYVAULT_NAME)
          SecretsFilter: $(TOKEN_NAME)

      - script: |
          API_TOKEN=$(githubAccessToken) \
          python UpdateDockerTags.py \
          $(REPO_OWNER) \
          $(REPO_NAME)
        displayName: 'Update Docker image tags'
        workingDirectory: $(WORKING_DIR)
