schedules:
- cron: "0 0 * * *"
  displayName: Daily Docker image tag update
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: UpdateDockerImageTags
  steps:
  - task: UsePythonVersion@0
    displayName: 'Install Python 3.7'
    inputs:
      versionSpec: '3.7'
      addToPath: true
  
  - script: 'python -m pip install -U pip setuptools wheel'
    displayName: 'Upgrade Python tools'
  
  - script: 'git clone https://github.com/HelmUpgradeBot/UpdateDockerTags.git'
    displayName: 'Clone UpdateDockerTags repo'

  - script: 'python -m pip install -r UpdateDockerTags/requirements.txt'
    displayName: 'Install UpdateDockerTags dependencies'

  - script: 'python UpdateDockerTags/setup.py install'
    displayName: 'Install UpdateDockerTags CLI'
