apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-shared-data-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
