apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-shared-data-pvc
  namespace: bridgehub
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 0.5Gi
