apiVersion: v1
kind: PersistentVolume
metadata:
  name: bridge-shared-data-pv
  namespace: bridgehub
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile
  azureFile:
    secretName: storage-secret
    shareName: bridge-shared-data
    readOnly: false
