apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-shared-data-claim
  namespace: bridgehub
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nfs
