apiVersion: v1
kind: PersistentVolume
metadata:
  name: bridge-shared-data-volume
  namespace: bridgehub
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.240.0.35
    path: /export/data
