name: Test on Minikube

on:
  pull_request:
    branches:
      - master

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.0
        with:
          minikube version: 'v1.5.2'
          kubernetes version: 'v1.15.5'
      - name: Interact with the cluster
        run: kubectl get nodes
